version: '3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql/data/:/var/lib/mysql
    env_file:
      - ./mysql-variables.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "13306:3306"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8081:8000"
    depends_on:
      - db
